### ISSUE TITLE
flash.tcl error

### ISSUE THREAD

**Issue by gregnix** [mittelmark/oowidgets#3]
Where is -flashtime configured?
I have the same problem in the tutorial.

https://github.com/mittelmark/oowidgets/tree/main/samples/flash.tcl

if line 148 is changed in the flash.tcl : if {true} {

Mixin for label flashed
unknown option "-flashtime"
    while executing
"$widget configure {*}$args"
    (class "::oowidgets::BaseWidget" method "configure" line 38)
    invoked from within
"my configure {*}$args"
    (class "::flash::Button" constructor line 3)
    invoked from within
"::flash::Button create tmp $path {*}$args"
    (procedure "flash::button" line 2)
    invoked from within
"flash::button .fb -text "Exit" -flashtime 100 -command exit"
    invoked from within
"if {true} {
    set fb [flash::button .fb -text "Exit" -flashtime 100 -command exit]
    pack $fb -side top -pady 10 -pady 10 -fill both -expand true
..."
    (file "flash.tcl" line 149)

**Comment by mittelmark** [comment]
Thanks for the error report. I think the problem was in oowidgets::BaseWidgets configure method, I now only delegate options which belong to the parent widget to the parent widget. That should fix this. Bumped version of oowidgets to 0.3.2.

**Comment by gregnix** [comment]
Thanks.
It works, bug fixed
Very interesting project

**Comment by mittelmark** [comment]
Ok, I close this then for now. Thanks for the feedback.
