### ISSUE TITLE
array options has a space between {*} and $args

### ISSUE THREAD

**Issue by gregnix** [mittelmark/oowidgets#5]
paul - basegui.tcl - constructor

line 125
  `array set options [list -style clam {*} $args]`
  
array options has a space between {*} and $args :

  `array set options [list -style clam {*}$args]`

**Comment by mittelmark** [comment]
Thanks for the comment!

 I fixed that in Git, will do a new release if there are no other problems. As well added paul.test to the tests folder to do more checks.

**Comment by gregnix** [comment]
Thank you for fixing the errors so quickly.
The issue can be closed.
