### ISSUE TITLE
Manual page about Paul

### ISSUE THREAD

**Issue by gregnix** [mittelmark/oowidgets#7]
On all manual pages about Paul the link to oowidgets manual is not correct.

`https://htmlpreview.github.io/?https://raw.githubusercontent.com/mittelmark/oowidgets/master/oowidgets.html`

an oowidgets is missing

`https://htmlpreview.github.io/?https://raw.githubusercontent.com/mittelmark/oowidgets/master/oowidgets/oowidgets.html`

**Comment by mittelmark** [comment]
Thanks for mentioning this. I think I fixed all the wrong oowidgets links for the Paul widgets, as far as I can see ...

**Comment by gregnix** [comment]
Thank for quickly fixing the wrong links.  The issue can be closed.
